"""
URL configuration for abst project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Import the include() function: from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def healthcheck(request):
    return JsonResponse({"status": "healthy", "message": "Django app is running"})

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("residents.urls")),
    path("api/", include("adls.urls")),
    path("api/", include("users.urls")),
    path("api/", include("scheduling.urls")),
    path("health/", healthcheck, name="healthcheck"),
]
