# Generated by Django 4.2.23 on 2025-10-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaycomSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_id", models.CharField(max_length=100, unique=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("employee_directory", "Employee Directory"),
                            ("employee_dates", "Employee Dates"),
                            ("employee_payees", "Employee Payees"),
                            ("all", "All Reports"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("files_processed", models.PositiveIntegerField(default=0)),
                ("files_successful", models.PositiveIntegerField(default=0)),
                ("files_failed", models.PositiveIntegerField(default=0)),
                ("employees_processed", models.PositiveIntegerField(default=0)),
                ("employees_created", models.PositiveIntegerField(default=0)),
                ("employees_updated", models.PositiveIntegerField(default=0)),
                ("employees_errors", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Paycom Sync Log",
                "verbose_name_plural": "Paycom Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PaycomFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.PositiveIntegerField()),
                ("file_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("downloaded", "Downloaded"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="downloaded",
                        max_length=20,
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("rows_processed", models.PositiveIntegerField(default=0)),
                ("rows_successful", models.PositiveIntegerField(default=0)),
                ("rows_failed", models.PositiveIntegerField(default=0)),
                (
                    "sync_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="paycom.paycomsynclog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paycom File",
                "verbose_name_plural": "Paycom Files",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PaycomEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("terminated", "Terminated"),
                            ("on_leave", "On Leave"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("department_code", models.CharField(blank=True, max_length=20)),
                (
                    "department_description",
                    models.CharField(blank=True, max_length=200),
                ),
                ("payroll_profile", models.CharField(blank=True, max_length=50)),
                (
                    "payroll_profile_description",
                    models.CharField(blank=True, max_length=200),
                ),
                ("location_code", models.CharField(blank=True, max_length=20)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("position_family", models.CharField(blank=True, max_length=100)),
                ("position_description", models.CharField(blank=True, max_length=200)),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("personal_phone", models.CharField(blank=True, max_length=20)),
                ("street_address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("zip_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("rehire_date", models.DateField(blank=True, null=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                ("employee_added_date", models.DateField(blank=True, null=True)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("pay_change_date", models.DateField(blank=True, null=True)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("overtime_eligible", models.BooleanField(default=True)),
                ("part_time_to_full_time", models.BooleanField(default=False)),
                ("cobra_start_date", models.DateField(blank=True, null=True)),
                ("on_leave_date", models.DateField(blank=True, null=True)),
                ("k401_eligibility", models.BooleanField(default=False)),
                ("k401_eligibility_date", models.DateField(blank=True, null=True)),
                (
                    "hours_worked_ytd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "hours_worked_current_period",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("max_hours_per_week", models.PositiveIntegerField(default=40)),
                ("paycom_employee_code", models.CharField(blank=True, max_length=50)),
                ("case_reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paycom_employee",
                        to="scheduling.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paycom Employee",
                "verbose_name_plural": "Paycom Employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
