# Generated by Django 4.2.23 on 2025-08-23 11:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("residents", "0003_resident_total_shift_times"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("cna", "Certified Nursing Assistant"),
                            ("lpn", "Licensed Practical Nurse"),
                            ("rn", "Registered Nurse"),
                            ("cna_float", "CNA Float"),
                            ("med_tech", "Medication Technician"),
                            ("caregiver", "Caregiver"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("on_leave", "On Leave"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "max_hours",
                    models.PositiveIntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="residents.facility",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("swing", "Swing"),
                            ("noc", "NOC"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2, help_text="Duration in hours", max_digits=4
                    ),
                ),
                (
                    "required_staff",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="residents.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["shift_type", "start_time"],
                "unique_together": {("facility", "template_name")},
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("required_staff_count", models.PositiveIntegerField(default=1)),
                ("required_staff_role", models.CharField(default="cna", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="residents.facility",
                    ),
                ),
                (
                    "shift_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="scheduling.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "shift_template__start_time"],
                "unique_together": {("facility", "date", "shift_template")},
            },
        ),
        migrations.CreateModel(
            name="StaffAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("no_overtime", "No Overtime"),
                            ("limited", "Limited Hours"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "max_hours",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                ("preferred_start_time", models.TimeField(blank=True, null=True)),
                ("preferred_end_time", models.TimeField(blank=True, null=True)),
                ("preferred_shift_types", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_availability",
                        to="residents.facility",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="scheduling.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Staff Availability",
                "ordering": ["date", "staff__last_name"],
                "unique_together": {("staff", "date", "facility")},
            },
        ),
        migrations.CreateModel(
            name="StaffAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="scheduling.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["shift__date", "shift__shift_template__start_time"],
                "unique_together": {("staff", "shift")},
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_type", models.CharField(max_length=20)),
                ("care_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("required_staff", models.PositiveIntegerField()),
                ("resident_count", models.PositiveIntegerField()),
                (
                    "confidence",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendations",
                        to="residents.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "shift_type"],
                "unique_together": {("facility", "date", "shift_type")},
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_residents", models.PositiveIntegerField()),
                (
                    "total_care_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "avg_acuity_score",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                (
                    "staffing_efficiency",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("low_acuity_count", models.PositiveIntegerField(default=0)),
                ("medium_acuity_count", models.PositiveIntegerField(default=0)),
                ("high_acuity_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insights",
                        to="residents.facility",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("facility", "date")},
            },
        ),
    ]
