# Generated by Django 4.2.23 on 2025-10-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0003_resident_total_shift_times"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyHoursSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("total_hours_worked", models.FloatField(default=0.0)),
                ("regular_hours", models.FloatField(default=0.0)),
                ("overtime_hours", models.FloatField(default=0.0)),
                (
                    "regular_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "overtime_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_overtime", models.BooleanField(default=False)),
                ("is_under_hours", models.BooleanField(default=False)),
                ("is_optimal_hours", models.BooleanField(default=True)),
                ("can_work_more", models.BooleanField(default=True)),
                ("should_avoid_overtime", models.BooleanField(default=False)),
                ("paycom_sync_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_hours",
                        to="scheduling.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weekly Hours Summary",
                "ordering": ["-week_start_date", "staff__last_name"],
                "unique_together": {("staff", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="TimeTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in", models.DateTimeField()),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("total_hours_worked", models.FloatField(default=0.0)),
                ("regular_hours", models.FloatField(default=0.0)),
                ("overtime_hours", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("clocked_in", "Clocked In"),
                            ("on_break", "On Break"),
                            ("clocked_out", "Clocked Out"),
                            ("no_show", "No Show"),
                        ],
                        default="clocked_in",
                        max_length=20,
                    ),
                ),
                ("paycom_sync_date", models.DateTimeField(blank=True, null=True)),
                ("paycom_employee_id", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_tracking",
                        to="residents.facility",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_tracking",
                        to="scheduling.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Time Tracking",
                "ordering": ["-date", "staff__last_name"],
                "unique_together": {("staff", "date")},
            },
        ),
    ]
