# Generated by Django 4.2.23 on 2025-10-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0003_resident_total_shift_times"),
        ("scheduling", "0002_weeklyhourssummary_timetracking"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="shift",
            name="required_staff_role",
            field=models.CharField(default="med_tech", max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={
                ("facility", "date", "shift_template", "required_staff_role")
            },
        ),
    ]
