# Generated by Django 4.2.23 on 2025-11-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_update_shift_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hourly pay rate from Paycom",
                max_digits=10,
                null=True,
            ),
        ),
    ]
