# Generated by Django 4.2.23 on 2025-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_staff_hourly_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifttemplate",
            name="shift_type",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("swing", "Swing"),
                    ("noc", "NOC"),
                    ("night", "Night"),
                    ("custom", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
