# Generated by Django 4.2.23 on 2025-07-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resident",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
