# Generated by Django 4.2.23 on 2025-12-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0003_resident_total_shift_times"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="adl_data_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
