# Generated by Django 4.2.23 on 2025-12-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0004_resident_adl_data_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="shift_format",
            field=models.CharField(
                choices=[
                    ("2_shift", "2-Shift (Day/Night - 12 hour shifts)"),
                    ("3_shift", "3-Shift (Day/Swing/NOC - 8 hour shifts)"),
                ],
                default="3_shift",
                help_text="2-shift: Day/Night (12hr shifts, Oregon). 3-shift: Day/Swing/NOC (8hr shifts, California)",
                max_length=20,
            ),
        ),
    ]
