# Generated by Django 4.2.23 on 2025-09-27 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("residents", "0003_resident_total_shift_times"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adls", "0003_adl_created_by_adl_updated_by_alter_adl_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyADLSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("total_adl_questions", models.PositiveIntegerField(default=0)),
                ("total_minutes_week", models.PositiveIntegerField(default=0)),
                ("total_hours_week", models.FloatField(default=0.0)),
                ("total_frequency_week", models.PositiveIntegerField(default=0)),
                ("adl_category_totals", models.JSONField(blank=True, default=dict)),
                ("is_complete", models.BooleanField(default=False)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_weekly_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_adl_summaries",
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_weekly_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start_date", "resident__name"],
                "unique_together": {("resident", "week_start_date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyADLEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("week_start_date", models.DateField()),
                ("week_end_date", models.DateField()),
                ("minutes_per_occurrence", models.PositiveIntegerField(default=0)),
                ("frequency_per_week", models.PositiveIntegerField(default=0)),
                ("total_minutes_week", models.PositiveIntegerField(default=0)),
                ("total_hours_week", models.FloatField(default=0.0)),
                ("per_day_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(blank=True, default="Complete", max_length=100),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "adl_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_entries",
                        to="adls.adlquestion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_weekly_adls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_adl_entries",
                        to="residents.resident",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_weekly_adls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-week_start_date",
                    "resident__name",
                    "adl_question__order",
                ],
                "unique_together": {("resident", "adl_question", "week_start_date")},
            },
        ),
    ]
