# Generated by Django 4.2.23 on 2025-10-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adls", "0004_weeklyadlsummary_weeklyadlentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyadlentry",
            name="status",
            field=models.CharField(blank=True, default="complete", max_length=100),
        ),
    ]
