# Generated by Django 4.2.23 on 2025-07-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facilityaccess",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Admin"),
                    ("admin", "Admin"),
                    ("facility_admin", "Facility Admin"),
                    ("staff", "Staff"),
                    ("readonly", "Read Only"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
